import type { BuildingDef } from './types';

/**
 * Bina kataloğu.
 *
 * Tasarım kuralı: her kademe daha çok kapasite ve kalite verir ama sabit
 * gideri de büyütür. Böylece "her zaman en büyüğünü yap" doğru cevap olmaz;
 * district'in talebi kadar kapasite kurmak gerekir.
 */
export const BUILDINGS: BuildingDef[] = [
  // ---- Market ----
  {
    id: 'corner_shop',
    name: 'Bakkal',
    role: 'outlet',
    category: 'grocery',
    tier: 1,
    cost: 31_000,
    upkeepPerDay: 90,
    capacity: 220,
    quality: 0.45,
    jobs: 3,
    radius: 0,
    color: '#5c9c62',
    height: 0.5,
    unlockNetWorth: 0,
    description: 'Küçük, ucuz, hızlı kurulur. Yoğun mahallelerde nakit akışı başlatır.',
  },
  {
    id: 'supermarket',
    name: 'Süpermarket',
    role: 'outlet',
    category: 'grocery',
    tier: 2,
    cost: 316_000,
    upkeepPerDay: 480,
    capacity: 1_400,
    quality: 0.68,
    jobs: 18,
    radius: 0,
    color: '#4e8f55',
    height: 0.9,
    unlockNetWorth: 500_000,
    description: 'Yüksek kapasite. Nüfusu kalabalık district\'lerde bakkalı ezer.',
  },
  // ---- Yeme-içme ----
  {
    id: 'cafe',
    name: 'Kafe',
    role: 'outlet',
    category: 'dining',
    tier: 1,
    cost: 116_000,
    upkeepPerDay: 140,
    capacity: 160,
    quality: 0.55,
    jobs: 5,
    radius: 0,
    color: '#d98f4a',
    height: 0.55,
    unlockNetWorth: 0,
    description: 'Yaya trafiğine duyarlı. Öğrenci ve turizm bölgelerinde güçlü.',
  },
  {
    id: 'restaurant',
    name: 'Restoran',
    role: 'outlet',
    category: 'dining',
    tier: 2,
    cost: 456_000,
    upkeepPerDay: 620,
    capacity: 480,
    quality: 0.78,
    jobs: 22,
    radius: 0,
    color: '#c47a35',
    height: 0.85,
    unlockNetWorth: 700_000,
    description: 'Yüksek marj, yüksek sabit gider. Gelir seviyesi yüksek bölge ister.',
  },
  // ---- Perakende ----
  {
    id: 'boutique',
    name: 'Butik',
    role: 'outlet',
    category: 'retail',
    tier: 1,
    cost: 91_000,
    upkeepPerDay: 260,
    capacity: 70,
    quality: 0.6,
    jobs: 6,
    radius: 0,
    color: '#a86fbb',
    height: 0.7,
    unlockNetWorth: 0,
    description: 'Küçük ama marjı iyi. Lüks konut ve turizm bölgelerinde parlar.',
  },
  {
    id: 'department_store',
    name: 'Mağazalar Zinciri',
    role: 'outlet',
    category: 'retail',
    tier: 2,
    cost: 1_229_000,
    upkeepPerDay: 1_800,
    capacity: 620,
    quality: 0.8,
    jobs: 60,
    radius: 0,
    color: '#8f56a3',
    height: 1.5,
    unlockNetWorth: 3_000_000,
    description: 'Şehrin perakende talebini tek noktada toplar. Ciddi sermaye ister.',
  },
  // ---- Elektronik ----
  {
    id: 'electronics_store',
    name: 'Elektronik Mağazası',
    role: 'outlet',
    category: 'electronics',
    tier: 1,
    cost: 96_000,
    upkeepPerDay: 700,
    capacity: 34,
    quality: 0.65,
    jobs: 12,
    radius: 0,
    color: '#4a9ac4',
    height: 0.9,
    unlockNetWorth: 300_000,
    description: 'Birim fiyatı yüksek. Teknopark ve merkez bölgelerde talep görür.',
  },
  // ---- Hizmet ----
  {
    id: 'gym',
    name: 'Spor Salonu',
    role: 'outlet',
    category: 'services',
    tier: 1,
    cost: 182_000,
    upkeepPerDay: 340,
    capacity: 130,
    quality: 0.6,
    jobs: 9,
    radius: 0,
    color: '#c9a83f',
    height: 0.75,
    unlockNetWorth: 150_000,
    description: 'Abonelik mantığıyla istikrarlı gelir. Orta gelir bölgelerinde iyi.',
  },
  // ---- Kira üreten varlıklar ----
  {
    id: 'apartment',
    name: 'Apartman',
    role: 'rental',
    category: 'housing',
    tier: 1,
    cost: 150_000,
    upkeepPerDay: 380,
    capacity: 90,
    quality: 0.6,
    jobs: 3,
    radius: 2,
    color: '#7488ab',
    height: 1.6,
    unlockNetWorth: 250_000,
    description: 'Kira geliri verir ve district nüfusunu artırır — kendi müşterini üretir.',
  },
  {
    id: 'office_tower',
    name: 'Plaza',
    role: 'rental',
    category: 'office',
    tier: 2,
    cost: 520_000,
    upkeepPerDay: 1_400,
    capacity: 210,
    quality: 0.75,
    jobs: 12,
    radius: 3,
    color: '#7d8ba0',
    height: 2.8,
    unlockNetWorth: 5_000_000,
    description: 'Yüksek kira geliri, çevredeki arsa değerini ve gündüz nüfusunu yükseltir.',
  },
  // ---- Operasyon ----
  {
    id: 'warehouse',
    name: 'Depo',
    role: 'logistics',
    category: 'grocery',
    tier: 1,
    cost: 76_000,
    upkeepPerDay: 420,
    capacity: 0,
    quality: 0,
    jobs: 14,
    radius: 8,
    color: '#6b7280',
    height: 0.8,
    unlockNetWorth: 800_000,
    description: 'Menzilindeki kendi mağazalarının satış maliyetini %12 düşürür.',
  },
  {
    id: 'factory',
    name: 'Fabrika',
    role: 'production',
    category: 'retail',
    tier: 1,
    cost: 310_000,
    upkeepPerDay: 1_600,
    capacity: 900,
    quality: 0,
    jobs: 90,
    radius: 12,
    color: '#8a6a4f',
    height: 1.1,
    unlockNetWorth: 4_000_000,
    description: 'Kendi perakende mağazalarına ucuz mal besler; tedariki dışarıdan almazsın.',
  },
];

export const BUILDING_BY_ID: Record<string, BuildingDef> = Object.fromEntries(
  BUILDINGS.map((b) => [b.id, b]),
);
