import type { NpcProfileDef } from './types';

/**
 * Rakip şirketler.
 *
 * Hepsi oyuncuyla aynı kurallara tabidir: aynı bina maliyetleri, aynı pazar
 * formülü, aynı nakit kısıtı. Fark sadece karar verirken neye ağırlık
 * verdikleri — yani kişilikleri. Görünmez avantaj yok.
 */
export const NPC_PROFILES: NpcProfileDef[] = [
  {
    id: 'nova_holding',
    name: 'Nova Holding',
    trait: 'expansionist',
    startingCash: 260_000,
    marginWeight: 0.4,
    demandWeight: 1.0,
    priceMultiplier: 1.0,
    aggression: 0.75,
    color: '#e2574c',
    description: 'Boşluk gördüğü her yere girer. Hızlı büyür, marjı umursamaz.',
    ceoName: 'Deniz Arkın',
    portrait: {
      skin: '#c9865c',
      hair: '#1d1614',
      hairStyle: 'crop',
      clothes: '#8c3a33',
      accent: '#e2574c',
      glasses: false,
      facialHair: true,
      background: '#3a1f1c',
    },
  },
  {
    id: 'kilit_market',
    name: 'Kilit Market',
    trait: 'price_cutter',
    startingCash: 220_000,
    marginWeight: 0.7,
    demandWeight: 0.8,
    priceMultiplier: 0.86,
    aggression: 0.55,
    color: '#e8913c',
    description: 'Fiyatı sürekli kırar. Aynı kategoride onunla fiyat savaşına girmek pahalıdır.',
    ceoName: 'Sema Bozkurt',
    portrait: {
      skin: '#e0b088',
      hair: '#5a3a1e',
      hairStyle: 'wave',
      clothes: '#8a5a22',
      accent: '#e8913c',
      glasses: true,
      facialHair: false,
      background: '#3d2a12',
    },
  },
  {
    id: 'meridyen',
    name: 'Meridyen Grup',
    trait: 'premium',
    startingCash: 300_000,
    marginWeight: 0.9,
    demandWeight: 0.6,
    priceMultiplier: 1.22,
    aggression: 0.45,
    color: '#c05fd8',
    description: 'Sadece yüksek gelirli bölgelere, yüksek fiyatla girer. Marka gücü yüksek.',
    ceoName: 'Ferit Alagöz',
    portrait: {
      skin: '#b57a52',
      hair: '#2b2028',
      hairStyle: 'short',
      clothes: '#6a3a78',
      accent: '#c05fd8',
      glasses: false,
      facialHair: false,
      background: '#2f1a36',
    },
  },
  {
    id: 'atlas_yapi',
    name: 'Atlas Yapı',
    trait: 'landlord',
    startingCash: 340_000,
    marginWeight: 0.5,
    demandWeight: 0.5,
    priceMultiplier: 1.0,
    aggression: 0.6,
    color: '#4bb3a5',
    description: 'Arsa toplar, kira üretir. Merkezi arsaları senden önce kapmaya çalışır.',
    ceoName: 'Nurgül Tekin',
    portrait: {
      skin: '#8f5f42',
      hair: '#20211f',
      hairStyle: 'bun',
      clothes: '#2c6b62',
      accent: '#4bb3a5',
      glasses: false,
      facialHair: false,
      background: '#16332f',
    },
  },
];
